**Research question**

Finding out the common states between three data sources on India


**Data Sources**

Data for the assignment has been obtained from these sources: 

1. Census of India
File Name: Primary Census Abstract Data Tables (India & States/UTs - District Level) (Excel Format) 
http://www.censusindia.gov.in/2011census/population_enumeration.html 

2. DHS: https://www.dhsprogram.com/data/dataset_admin/index.cfm
India 2015-16 (access required)
File Name: IAPR74FL.DTA inside the folder DHS_HH Member
open in STATA and convert to .csv

3. Indian Human Development Survey: https://www.icpsr.umich.edu/icpsrweb/DSDR/studies/36151/summary
(download all 14 folders)
File Name: 36151-0001-Data.dta inside the folder DS0001
open in STATA and convert to .csv



**Codebooks**

Census: "State" refers to the list of states in India 
IHDS: "STATEID" refers to the list of states in India 
DHS: "hv024" refers to the list of states in India 


**Data Formats**

Census: excel 
IHDS: .dta converted to .csv
DHS: dta converted to .csv

In [0]:
import pandas as pd
pd.read_csv("ihds_state.csv")
pd.read_csv("dhs_state.csv")
pd.read_excel("census_state.xlsx")

,EB,Level,State,TRU,No_HH,TOT_P,TOT_M,TOT_F,P_06,M_06,...,MARG_AL_0_3_F,MARG_HH_0_3_P,MARG_HH_0_3_M,MARG_HH_0_3_F,MARG_OT_0_3_P,MARG_OT_0_3_M,MARG_OT_0_3_F,NON_WORK_P,NON_WORK_M,NON_WORK_F
0,0,India,India,Total,249501663,1210854977,623270258,587584719,164515253,85752254,...,5820403,1420348,491424,928924,5518450,3082613,2435837,728966109,291330383,437635726
1,0,India,India,Rural,168612897,833748852,427781058,405967794,121322865,63084449,...,5640822,1154975,386077,768898,3803400,1972348,1831052,485005760,200944045,284061715
2,0,India,India,Urban,80888766,377106125,195489200,181616925,43192388,22667805,...,179581,265373,105347,160026,1715050,1110265,604785,243960349,90386338,153574011
3,0,STATE,JAMMU & KASHMIR,Total,2119718,12541302,6640662,5900640,2018905,1084355,...,44570,26585,6780,19805,108457,56880,51577,8218589,3445572,4773017
4,0,STATE,JAMMU & KASHMIR,Rural,1553433,9108060,4774477,4333583,1593008,854141,...,40936,21963,5757,16206,89232,45625,43607,5994979,2562471,3432508
5,0,STATE,JAMMU & KASHMIR,Urban,566285,3433242,1866185,1567057,425897,230214,...,3634,4622,1023,3599,19225,11255,7970,2223610,883101,1340509
6,0,DISTRICT,Kupwara,Total,113929,870354,474190,396164,188798,100459,...,1955,1216,597,619,7369,4727,2642,641290,283291,357999
7,0,DISTRICT,Kupwara,Rural,101930,765625,412038,353587,169588,90235,...,1893,1130,556,574,6644,4149,2495,569632,250046,319586
8,0,DISTRICT,Kupwara,Urban,11999,104729,62152,42577,19210,10224,...,62,86,41,45,725,578,147,71658,33245,38413
9,0,DISTRICT,Badgam,Total,103363,753745,398041,355704,155202,84720,...,2035,3823,1148,2675,4674,2393,2281,538879,235463,303416
10,0,DISTRICT,Badgam,Rural,89417,655833,343385,312448,140608,76753,...,2000,3652,1107,2545,3585,1740,1845,474065,208816,265249
11,0,DISTRICT,Badgam,Urban,13946,97912,54656,43256,14594,7967,...,35,171,41,130,1089,653,436,64814,26647,38167
12,0,DISTRICT,Leh(Ladakh),Total,21909,133487,78971,54516,12016,6174,...,106,65,17,48,633,416,217,58408,25706,32702
13,0,DISTRICT,Leh(Ladakh),Rural,14905,87816,48411,39405,9053,4684,...,92,63,16,47,423,291,132,39435,17482,21953
14,0,DISTRICT,Leh(Ladakh),Urban,7004,45671,30560,15111,2963,1490,...,14,2,1,1,210,125,85,18973,8224,10749
15,0,DISTRICT,Kargil,Total,18338,140802,77785,63017,19928,10078,...,521,263,93,170,3887,2920,967,88929,37946,50983
16,0,DISTRICT,Kargil,Rural,16147,124464,67703,56761,18359,9290,...,521,246,87,159,3742,2784,958,80004,33999,46005
17,0,DISTRICT,Kargil,Urban,2191,16338,10082,6256,1569,788,...,0,17,6,11,145,136,9,8925,3947,4978
18,0,DISTRICT,Punch,Total,90261,476835,251899,224936,84674,44733,...,2035,948,243,705,6374,2762,3612,315442,134222,181220
19,0,DISTRICT,Punch,Rural,83045,438205,229774,208431,80241,42380,...,2008,945,243,702,6235,2702,3533,291016,123712,167304
20,0,DISTRICT,Punch,Urban,7216,38630,22125,16505,4433,2353,...,27,3,0,3,139,60,79,24426,10510,13916
21,0,DISTRICT,Rajouri,Total,130401,642415,345351,297064,108271,58051,...,2424,861,217,644,15078,4583,10495,351503,160599,190904
22,0,DISTRICT,Rajouri,Rural,122645,590101,310748,279353,103424,55404,...,2414,806,211,595,14775,4386,10389,326714,150214,176500
23,0,DISTRICT,Rajouri,Urban,7756,52314,34603,17711,4847,2647,...,10,55,6,49,303,197,106,24789,10385,14404
24,0,DISTRICT,Kathua,Total,119583,616435,326109,290326,83936,45833,...,887,325,161,164,4444,3410,1034,416004,164561,251443
25,0,DISTRICT,Kathua,Rural,101651,526722,278126,248596,74401,40571,...,887,316,154,162,4138,3150,988,354069,140274,213795
26,0,DISTRICT,Kathua,Urban,17932,89713,47983,41730,9535,5262,...,0,9,7,2,306,260,46,61935,24287,37648
27,0,DISTRICT,Baramula,Total,152635,1008039,534733,473306,164581,88321,...,3141,1701,787,914,6955,4606,2349,703839,285152,418687
28,0,DISTRICT,Baramula,Rural,125346,825539,432399,393140,142524,76404,...,3114,1648,757,891,6224,4038,2186,587506,240606,346900
29,0,DISTRICT,Baramula,Urban,27289,182500,102334,80166,22057,11917,...,27,53,30,23,731,568,163,116333,44546,71787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,0,DISTRICT,Tiruppur,Total,712210,2479052,1246159,1232893,241351,123612,...,2024,1044,238,806,7776,3872,3904,1212915,426376,786539
1999,0,DISTRICT,Tiruppur,Rural,283187,957941,479309,478632,79787,40947,...,1593,487,124,363,2320,959,1361,409383,156563,252820
2000,0,DISTRICT,Tiruppur,Urban,429023,1521111,766850,754261,161564,82665,...,431,557,114,443,5456,2913,2543,803532,269813,533719
2001,0,STATE,PUDUCHERRY,Total,302450,1247953,612511,635442,132858,67527,...,2189,403,135,268,4618,2831,1787,802985,279580,523405
2002,0,STATE,PUDUCHERRY,Rural,95018,395200,194907,200293,44514,22798,...,1908,188,71,117,1713,1029,684,247324,89202,158122
2003,0,STATE,PUDUCHERRY,Urban,207432,852753,417604,435149,88344,44729,...,281,215,64,151,2905,1802,1103,555661,190378,365283
2004,0,DISTRICT,Yanam,Total,13812,55626,27301,28325,6204,3230,...,29,6,2,4,163,94,69,38866,13254,25612
2005,0,DISTRICT,Yanam,Rural,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2006,0,DISTRICT,Yanam,Urban,13812,55626,27301,28325,6204,3230,...,29,6,2,4,163,94,69,38866,13254,25612
2007,0,DISTRICT,Puducherry,Total,231513,950289,468258,482031,99838,50688,...,1776,296,116,180,3259,2054,1205,602184,211606,390578
2008,0,DISTRICT,Puducherry,Rural,69497,293080,144769,148311,33003,16896,...,1626,129,58,71,1234,758,476,180600,66171,114429
2009,0,DISTRICT,Puducherry,Urban,162016,657209,323489,333720,66835,33792,...,150,167,58,109,2025,1296,729,421584,145435,276149
2010,0,DISTRICT,Mahe,Total,7420,41816,19143,22673,4553,2302,...,1,1,0,1,160,78,82,30014,10050,19964
2011,0,DISTRICT,Mahe,Rural,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2012,0,DISTRICT,Mahe,Urban,7420,41816,19143,22673,4553,2302,...,1,1,0,1,160,78,82,30014,10050,19964
2013,0,DISTRICT,Karaikal,Total,49705,200222,97809,102413,22263,11307,...,383,100,17,83,1036,605,431,131921,44670,87251
2014,0,DISTRICT,Karaikal,Rural,25521,102120,50138,51982,11511,5902,...,282,59,13,46,479,271,208,66724,23031,43693
2015,0,DISTRICT,Karaikal,Urban,24184,98102,47671,50431,10752,5405,...,101,41,4,37,557,334,223,65197,21639,43558
2016,0,STATE,ANDAMAN & NICOBAR ISLANDS,Total,94551,380581,202871,177710,40878,20770,...,204,559,282,277,3774,2576,1198,228046,81982,146064
2017,0,STATE,ANDAMAN & NICOBAR ISLANDS,Rural,58530,237093,126287,110806,26415,13370,...,202,553,278,275,3170,2150,1020,142624,51617,91007
2018,0,STATE,ANDAMAN & NICOBAR ISLANDS,Urban,36021,143488,76584,66904,14463,7400,...,2,6,4,2,604,426,178,85422,30365,55057
2019,0,DISTRICT,Nicobars,Total,9288,36842,20727,16115,4389,2256,...,21,481,237,244,1346,946,400,19717,8013,11704
2020,0,DISTRICT,Nicobars,Rural,9288,36842,20727,16115,4389,2256,...,21,481,237,244,1346,946,400,19717,8013,11704
2021,0,DISTRICT,Nicobars,Urban,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2022,0,DISTRICT,North & Middle Andaman,Total,26199,105597,54861,50736,11828,5991,...,120,30,21,9,1117,697,420,67018,24249,42769
2023,0,DISTRICT,North & Middle Andaman,Rural,25475,102856,53457,49399,11579,5873,...,119,30,21,9,1047,654,393,65311,23633,41678
2024,0,DISTRICT,North & Middle Andaman,Urban,724,2741,1404,1337,249,118,...,1,0,0,0,70,43,27,1707,616,1091
2025,0,DISTRICT,South Andaman,Total,59064,238142,127283,110859,24661,12523,...,63,48,24,24,1311,933,378,141311,49720,91591
2026,0,DISTRICT,South Andaman,Rural,23767,97395,52103,45292,10447,5241,...,62,42,20,22,777,550,227,57596,19971,37625
2027,0,DISTRICT,South Andaman,Urban,35297,140747,75180,65567,14214,7282,...,1,6,4,2,534,383,151,83715,29749,53966

In [0]:
census_state = pd.read_excel("census_state.xlsx")

dhs_state = pd.read_csv("dhs_state.csv")

ihds_state = pd.read_csv("ihds_state.csv")


print(census_state.head())

print(dhs_state.head())

print (ihds_state.head())

   EB  Level            State    TRU      No_HH       TOT_P      TOT_M  \
0   0  India            India  Total  249501663  1210854977  623270258
1   0  India            India  Rural  168612897   833748852  427781058
2   0  India            India  Urban   80888766   377106125  195489200
3   0  STATE  JAMMU & KASHMIR  Total    2119718    12541302    6640662
4   0  STATE  JAMMU & KASHMIR  Rural    1553433     9108060    4774477

       TOT_F       P_06      M_06     ...      MARG_AL_0_3_F  MARG_HH_0_3_P  \
0  587584719  164515253  85752254     ...            5820403        1420348
1  405967794  121322865  63084449     ...            5640822        1154975
2  181616925   43192388  22667805     ...             179581         265373
3    5900640    2018905   1084355     ...              44570          26585
4    4333583    1593008    854141     ...              40936          21963

   MARG_HH_0_3_M  MARG_HH_0_3_F  MARG_OT_0_3_P  MARG_OT_0_3_M  MARG_OT_0_3_F  \
0         491424         928924        5518450        3082613        2435837
1         386077         768898        3803400        1972348        1831052
2         105347         160026        1715050        1110265         604785
3           6780          19805         108457          56880          51577
4           5757          16206          89232          45625          43607

   NON_WORK_P  NON_WORK_M  NON_WORK_F
0   728966109   291330383   437635726
1   485005760   200944045   284061715
2   243960349    90386338   153574011
3     8218589     3445572     4773017
4     5994979     2562471     3432508

[5 rows x 89 columns]
                         hv024
0  andaman and nicobar islands
1  andaman and nicobar islands
2  andaman and nicobar islands
3  andaman and nicobar islands
4  andaman and nicobar islands
              STATEID
0  Jammu & Kashmir 01
1  Jammu & Kashmir 01
2  Jammu & Kashmir 01
3  Jammu & Kashmir 01
4  Jammu & Kashmir 01

In [0]:
print(list(census_state))
print(list(dhs_state))
print(list(ihds_state))

['EB', 'Level', 'State', 'TRU', 'No_HH', 'TOT_P', 'TOT_M', 'TOT_F', 'P_06', 'M_06', 'F_06', 'P_SC', 'M_SC', 'F_SC', 'P_ST', 'M_ST', 'F_ST', 'P_LIT', 'M_LIT', 'F_LIT', 'P_ILL', 'M_ILL', 'F_ILL', 'TOT_WORK_P', 'TOT_WORK_M', 'TOT_WORK_F', 'MAINWORK_P', 'MAINWORK_M', 'MAINWORK_F', 'MAIN_CL_P', 'MAIN_CL_M', 'MAIN_CL_F', 'MAIN_AL_P', 'MAIN_AL_M', 'MAIN_AL_F', 'MAIN_HH_P', 'MAIN_HH_M', 'MAIN_HH_F', 'MAIN_OT_P', 'MAIN_OT_M', 'MAIN_OT_F', 'MARGWORK_P', 'MARGWORK_M', 'MARGWORK_F', 'MARG_CL_P', 'MARG_CL_M', 'MARG_CL_F', 'MARG_AL_P', 'MARG_AL_M', 'MARG_AL_F', 'MARG_HH_P', 'MARG_HH_M', 'MARG_HH_F', 'MARG_OT_P', 'MARG_OT_M', 'MARG_OT_F', 'MARGWORK_3_6_P', 'MARGWORK_3_6_M', 'MARGWORK_3_6_F', 'MARG_CL_3_6_P', 'MARG_CL_3_6_M', 'MARG_CL_3_6_F', 'MARG_AL_3_6_P', 'MARG_AL_3_6_M', 'MARG_AL_3_6_F', 'MARG_HH_3_6_P', 'MARG_HH_3_6_M', 'MARG_HH_3_6_F', 'MARG_OT_3_6_P', 'MARG_OT_3_6_M', 'MARG_OT_3_6_F', 'MARGWORK_0_3_P', 'MARGWORK_0_3_M', 'MARGWORK_0_3_F', 'MARG_CL_0_3_P', 'MARG_CL_0_3_M', 'MARG_CL_0_3_F', 'MARG_AL_0_3_P', 'MARG_AL_0_3_M', 'MARG_AL_0_3_F', 'MARG_HH_0_3_P', 'MARG_HH_0_3_M', 'MARG_HH_0_3_F', 'MARG_OT_0_3_P', 'MARG_OT_0_3_M', 'MARG_OT_0_3_F', 'NON_WORK_P', 'NON_WORK_M', 'NON_WORK_F']
['hv024']
['STATEID']

In [0]:
census_state_col = census_state[["State"]]
print(census_state_col.sample(15))

ihds_state_col = ihds_state[["STATEID"]]
print(ihds_state_col.sample(15))

dhs_state_col = dhs_state[["hv024"]]
print(dhs_state_col.sample(15))

           State
1706    Warangal
529     Lalitpur
788   West Siang
1697  Rangareddy
1538     Bharuch
653    Madhubani
826   Mokokchung
414      Udaipur
1807      Mandya
754       SIKKIM
1648  Ahmadnagar
1447  Ashoknagar
1437       Seoni
576        Gonda
78        Kangra
                    STATEID
167797    Andhra Pradesh 28
19296         Chandigarh 04
51528      Uttar Pradesh 09
27615            Haryana 06
170006    Andhra Pradesh 28
151161       Maharashtra 27
115223      Chhattisgarh 22
66749      Uttar Pradesh 09
122944    Madhya Pradesh 23
151432       Maharashtra 27
6267    Himachal Pradesh 02
177471         Karnataka 29
170722    Andhra Pradesh 28
137397           Gujarat 24
181586         Karnataka 29
                               hv024
474099                  chhattisgarh
1313974               madhya pradesh
548040                       gujarat
2779816                  west bengal
1425150                  maharashtra
525713                 daman and diu
950001                     jharkhand
2752287                  uttarakhand
2107141                    rajasthan
2119490                    rajasthan
2649592                uttar pradesh
1494690                  maharashtra
2729227                  uttarakhand
4984     andaman and nicobar islands
999448                     karnataka

census_ihds = census_state_col.merge(ihds_state_col, left_on='State' , right_on='STATEID', how="outer")

In [0]:

census_state_fnl = pd.DataFrame(census_state_col.drop_duplicates()['State'].str.lower())
print(census_state_fnl)

dhs_state_fnl = pd.DataFrame(dhs_state_col.drop_duplicates()['hv024'].str.lower())
print(dhs_state_fnl)

ihds_state_fnl = pd.DataFrame(ihds_state_col.drop_duplicates()['STATEID'].str.lower())
print(ihds_state_fnl)

                          State
0                         india
3               jammu & kashmir
6                       kupwara
9                        badgam
12                  leh(ladakh)
15                       kargil
18                        punch
21                      rajouri
24                       kathua
27                     baramula
30                    bandipore
33                     srinagar
36                    ganderbal
39                      pulwama
42                     shupiyan
45                     anantnag
48                       kulgam
51                         doda
54                       ramban
57                     kishtwar
60                     udhampur
63                        reasi
66                        jammu
69                        samba
72             himachal pradesh
75                       chamba
78                       kangra
81                lahul & spiti
84                        kullu
87                        mandi
...                         ...
1938                     karur
1941            tiruchirappalli
1944               perambalur
1947                 ariyalur
1950                  cuddalore
1953             nagapattinam
1956                 thiruvarur
1959                  thanjavur
1962                pudukkottai
1965                  sivaganga
1968                    madurai
1971                    theni
1974               virudhunagar
1977             ramanathapuram
1980               thoothukkudi
1983               tirunelveli
1986              kanniyakumari
1989                 dharmapuri
1992                krishnagiri
1995                 coimbatore
1998                   tiruppur
2001                 puducherry
2004                      yanam
2007                 puducherry
2010                       mahe
2013                   karaikal
2016  andaman & nicobar islands
2019                   nicobars
2022    north  & middle andaman
2025              south andaman

[670 rows x 1 columns]
                               hv024
0        andaman and nicobar islands
10462                 andhra pradesh
52169              arunachal pradesh
111628                         assam
224692                         bihar
422851                    chandigarh
426089                  chhattisgarh
522069        dadra and nagar haveli
525522                 daman and diu
531511                           goa
537881                       gujarat
635692                       haryana
723719              himachal pradesh
764109             jammu and kashmir
857900                     jharkhand
985216                     karnataka
1092423                       kerala
1138085                  lakshadweep
1142125               madhya pradesh
1403637                  maharashtra
1530834                      manipur
1586572                    meghalaya
1624042                      mizoram
1675407                     nagaland
1721635                        delhi
1749008                       odisha
1879205                   puducherry
1892784                       punjab
1970807                    rajasthan
2148283                       sikkim
2167164                   tamil nadu
2268272                      tripura
2286432                uttar pradesh
2701404                  uttarakhand
2769845                  west bengal
2837771                    telangana
                      STATEID
0          jammu & kashmir 01
4125      himachal pradesh 02
10737               punjab 03
19184           chandigarh 04
19542          uttarakhand 05
21882              haryana 06
31450                delhi 07
36086            rajasthan 08
50426        uttar pradesh 09
71972                bihar 10
80467               sikkim 11
80970    arunachal pradesh 12
81638             nagaland 13
82146              manipur 14
82627              mizoram 15
82974              tripura 16
83893            meghalaya 17
84579                assam 18
89230          west bengal 19
99801            jharkhand 20
104243              orissa 21
114266        chhattisgarh 22
120589      madhya pradesh 23
135752             gujarat 24
145116         daman & diu 25
145388  dadra+nagar haveli 26
145702         maharashtra 27
161686      andhra pradesh 28
170790           karnataka 29
188980                 goa 30
189737              kerala 32
196517          tamil nadu 33
204151         pondicherry 34

In [0]:
ihds_state_new = pd.DataFrame(ihds_state_fnl['STATEID'].apply(lambda x:x[:-3]))
print(ihds_state_new)

                   STATEID
0          jammu & kashmir
4125      himachal pradesh
10737               punjab
19184           chandigarh
19542          uttarakhand
21882              haryana
31450                delhi
36086            rajasthan
50426        uttar pradesh
71972                bihar
80467               sikkim
80970    arunachal pradesh
81638             nagaland
82146              manipur
82627              mizoram
82974              tripura
83893            meghalaya
84579                assam
89230          west bengal
99801            jharkhand
104243              orissa
114266        chhattisgarh
120589      madhya pradesh
135752             gujarat
145116         daman & diu
145388  dadra+nagar haveli
145702         maharashtra
161686      andhra pradesh
170790           karnataka
188980                 goa
189737              kerala
196517          tamil nadu
204151         pondicherry

In [0]:
census_dhs = census_state_fnl.merge(dhs_state_fnl, left_on='State', right_on='hv024')
print(census_dhs)

census_dhs_ihds = census_dhs.merge(ihds_state_new, left_on='State' , right_on='STATEID')
print(census_dhs_ihds)

                State              hv024
0    himachal pradesh   himachal pradesh
1              punjab             punjab
2          chandigarh         chandigarh
3          chandigarh         chandigarh
4         uttarakhand        uttarakhand
5             haryana            haryana
6           rajasthan          rajasthan
7       uttar pradesh      uttar pradesh
8               bihar              bihar
9              sikkim             sikkim
10  arunachal pradesh  arunachal pradesh
11           nagaland           nagaland
12            manipur            manipur
13            mizoram            mizoram
14            tripura            tripura
15          meghalaya          meghalaya
16              assam              assam
17        west bengal        west bengal
18          jharkhand          jharkhand
19             odisha             odisha
20       chhattisgarh       chhattisgarh
21     madhya pradesh     madhya pradesh
22            gujarat            gujarat
23        maharashtra        maharashtra
24     andhra pradesh     andhra pradesh
25          karnataka          karnataka
26                goa                goa
27        lakshadweep        lakshadweep
28        lakshadweep        lakshadweep
29             kerala             kerala
30         tamil nadu         tamil nadu
31         puducherry         puducherry
32         puducherry         puducherry
                State              hv024            STATEID
0    himachal pradesh   himachal pradesh   himachal pradesh
1              punjab             punjab             punjab
2          chandigarh         chandigarh         chandigarh
3          chandigarh         chandigarh         chandigarh
4         uttarakhand        uttarakhand        uttarakhand
5             haryana            haryana            haryana
6           rajasthan          rajasthan          rajasthan
7       uttar pradesh      uttar pradesh      uttar pradesh
8               bihar              bihar              bihar
9              sikkim             sikkim             sikkim
10  arunachal pradesh  arunachal pradesh  arunachal pradesh
11           nagaland           nagaland           nagaland
12            manipur            manipur            manipur
13            mizoram            mizoram            mizoram
14            tripura            tripura            tripura
15          meghalaya          meghalaya          meghalaya
16              assam              assam              assam
17        west bengal        west bengal        west bengal
18          jharkhand          jharkhand          jharkhand
19       chhattisgarh       chhattisgarh       chhattisgarh
20     madhya pradesh     madhya pradesh     madhya pradesh
21            gujarat            gujarat            gujarat
22        maharashtra        maharashtra        maharashtra
23     andhra pradesh     andhra pradesh     andhra pradesh
24          karnataka          karnataka          karnataka
25                goa                goa                goa
26             kerala             kerala             kerala
27         tamil nadu         tamil nadu         tamil nadu